#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia64_ifort+mpi_altix_nas,v 1.23 2013/07/22 18:40:45 jmc Exp $
# $Name:  $

# tested on columbia using:
# module purge
# module add intel-parallel-studio/2015
FC=mpiifort
CC=mpiicc

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'

# /vega/opt/parallel_studio_xe_2015_update1/composer_xe_2015.1.133/mpirt/lib/intel64
# /vega/opt/parallel_studio_xe_2015_update1/impi/5.0.2.044/include64/
# /vega/opt/parallel_studio_xe_2015_update1/impi/5.0.2.044/lib64
#LIBS='-L/opt/sgi/mpt/1.16.0.0/lib -lmpi -L/opt/pd/netcdf/3.6.0-p1/lib -lnetcdf'
#INCLUDES='-I/opt/sgi/mpt/1.16.0.0/include -I/opt/pd/netcdf/3.6.0-p1/include'
#INCLUDEDIRS='/opt/sgi/mpt/1.16.0.0/include'

LIBS='-L/vega/opt/parallel_studio_xe_2015_update1/impi/5.0.2.044/lib64 -lmpi -lnetcdf'
INCLUDES='-I/vega/opt/parallel_studio_xe_2015_update1/impi/5.0.2.044/include64'
INCLUDEDIRS='/vega/opt/parallel_studio_xe_2015_update1/impi/5.0.2.044/include64'

#- used for parallel (MPI) DIVA
#MPIINCLUDEDIR='/opt/sgi/mpt/1.16.0.0/include'
#MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'

#PAPIINC='-I/usr/local/include'
#PAPILIB='-L/usr/local/lib -lpapi'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
#    FFLAGS="$FFLAGS -fp-model precise -ftz -w95 -W0 -WB -convert big_endian -assume byterecl"
    FFLAGS="$FFLAGS -WB -convert big_endian -assume byterecl"
    FOPTIM='-O2 -align -march=corei7 -axAVX'
    NOOPTFLAGS='-O1'
    NOOPTFILES='calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -w95 -W0 -WB -convert big_endian -assume byterecl"
    FOPTIM='-O0 -noalign'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

