#!/bin/bash

# module purge
# module add shared intel-parallel-studio
FC=mpiifort
CC=mpiicc

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'

LIBS="-L$I_MPI_ROOT/lib64 -lmpi $(nf-config --flibs)"
INCLUDES="-I$I_MPI_ROOT/include64 $(nf-config --fflags)"
INCLUDEDIRS="$I_MPI_ROOT/include64 $(nf-config --includedir)"



#- used for parallel (MPI) DIVA
#MPIINCLUDEDIR='/opt/sgi/mpt/1.16.0.0/include'
#MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'

#PAPIINC='-I/usr/local/include'
#PAPILIB='-L/usr/local/lib -lpapi'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
#    FFLAGS="$FFLAGS -fp-model precise -ftz -w95 -W0 -WB -convert big_endian -assume byterecl"
    FFLAGS="$FFLAGS -WB -convert big_endian -assume byterecl -mcmodel=medium -shared-intel"
    FOPTIM='-O3 -align -march=corei7 -axAVX'
    NOOPTFLAGS='-O1'
    NOOPTFILES='calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl -mcmodel=medium -shared-intel"
    FOPTIM='-O0 -noalign'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

